### ISSUE TITLE
Some ucs modules missing from collection?

### ISSUE THREAD

**Issue by gundalow** [CiscoDevNet/ansible-ucs#2]
Hi
I notice that there are some ucs modules that are in ansile/ansible:devel today that are not included in this collection.

Modules and plugins that are not "claimed" by a specific Collection will end up in `community.general`

### UCS modules left in community.general
```
cd community.general 
grep -l cisco.ucs plugins/
plugins/modules/remote_management/ucs/ucs_dns_server.py
plugins/modules/remote_management/ucs/ucs_storage_profile.py
plugins/modules/remote_management/ucs/ucs_san_connectivity.py
plugins/modules/remote_management/ucs/ucs_vhba_template.py
plugins/modules/remote_management/ucs/ucs_vnic_template.py
plugins/modules/remote_management/ucs/ucs_timezone.py
plugins/modules/remote_management/ucs/ucs_disk_group_policy.py
plugins/modules/remote_management/ucs/ucs_lan_connectivity.py
plugins/modules/remote_management/ucs/ucs_wwn_pool.py
plugins/modules/remote_management/ucs/ucs_vsans.py
plugins/modules/remote_management/ucs/ucs_ntp_server.py
plugins/modules/remote_management/ucs/ucs_vlan_find.py
plugins/modules/remote_management/ucs/ucs_org.py

```

### Next steps

Assuming these files *should* be in this collection

1) PR1
Add these files to the `ucs:` section of https://github.com/ansible-community/collection_migration/blob/master/scenarios/nwo/cisco.yml
Remove the same files from https://github.com/ansible-community/collection_migration/blob/master/scenarios/nwo/community.yml

This is needed by **Friday 6th March**

2) PRs 
Add those PRs to this collection (and update Python imports, etc as needed)
cc @dsoper2 @movinalot

**Comment by movinalot** [comment]
These modules are being added to the collection today. They do not need to be part of the community.general collection.

**Comment by movinalot** [comment]
Yes, edits made PRs created.
