### ISSUE TITLE
Sanity tests failing in cisco.ucs

### ISSUE THREAD

**Issue by dmsimard** [CiscoDevNet/ansible-ucs#34]
##### SUMMARY
We are running sanity tests across every collection included in the Ansible community package (as part of [this issue](https://github.com/ansible-community/community-topics/issues/96)) and found that ``ansible-test sanity --docker`` against cisco.ucs 1.8.0 fails with ansible-core 2.13.0rc1 in ansible 6.0.0a2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
n/a

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.0rc1]
```

##### COLLECTION VERSION

```paste below
1.8.0
```

##### STEPS TO REPRODUCE

```yaml
ansible-test sanity --docker
```

##### EXPECTED RESULTS

Tests are either passing or ignored.

##### ACTUAL RESULTS

List of failures is too long to be included in this issue, see this gist: https://gist.githubusercontent.com/dmsimard/f1617d6eea84102d34572f15ea931904/raw/a804740be87905e96b98f2f56ccd2f4334459151/output.txt

**Comment by dsoper2** [comment]
CI added and ansible-test sanity now passing
