### ISSUE TITLE
ansible-test sanity issues

### ISSUE THREAD

**Issue by mariolenz** [CiscoDevNet/ansible-ucs#37]
`ansible-test sanity` seems to fail with a lot of errors like:

```
ERROR: plugins/modules/ucs_uuid_pool.py:0:0: parameter-type-not-in-doc: Argument 'disk_policy_name' in argument_spec found in local_luns defines type as 'str' but documentation doesn't define type
```

All in all, 6 sanity tests seem to fail:

```
FATAL: The 6 sanity test(s) listed below (out of 46) failed. See error output above for details.
future-import-boilerplate
import --python 3.10
metaclass-boilerplate
pep8
pylint
validate-modules
```

Since this collection is part the Ansible (community) package 8, please make sure that the sanity tests succeed with ansible-core 2.15.x that it is based on.

BTW: There seem to be no regular / automatic sanity tests. However, I think we kind of require them. See [CI Testing](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#ci-testing) for more information.

In case you fix this, please do a new release. The community package includes collections via galaxy so just fixing this in your repo doesn't really help us.

**Comment by dsoper2** [comment]
Version 1.9.0 published to galaxy with fixes for all issues except validate-modules which we'll address in the next release.

**Comment by dsoper2** [comment]
CI added and ansible-test sanity now passing
